services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./:/app  
    environment:
      - HOLA=MUNDO
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - redlocal

networks:
  redlocal:

